# Get K3S_TOKEN from .env file
env_file_path = File.join(File.dirname(__FILE__), '.env')
if File.exist?(env_file_path)
  File.read(env_file_path).each_line do |line|
    key, value = line.strip.split('=')
    ENV[key] = value
  end
end

Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-12"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
    v.gui = false
  end

  config.vm.define "dvergobbS" do |server|
    server.vm.hostname = "dvergobbS"
    server.vm.network "private_network", bridge: "eth1", ip: "192.168.56.110"
    server.vm.provision "shell", inline: <<-SHELL
      # Script for Server
      sudo apt-get update -qq 
      sudo apt-get install -qq -y curl net-tools

      # Install Docker
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh 2>&1 >/dev/null
      sudo usermod -aG docker vagrant

      # Add /sbin to the PATH for the user vagrant
      echo 'export PATH=$PATH:/sbin' >> /home/vagrant/.bashrc
      source /home/vagrant/.bashrc

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip 192.168.56.110" \
        K3S_TOKEN="#{ENV['K3S_TOKEN']}" \
        K3S_KUBECONFIG_MODE="644" sh -s -

      # Deployments and Services
      kubectl apply -f /vagrant/conf/deployement.yaml
      kubectl apply -f /vagrant/conf/service.yaml
      kubectl apply -f /vagrant/conf/ingress.yaml
    SHELL
  end
end
