Vagrant.configure(2) do |config|
  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"
  # config.vm.box = "centos/7" // Timeout, surement à cause de M1
  config.vm.synced_folder "shared", "/vagrant_shared", create: true

  config.vm.provider :vmware_desktop do |vmware|
    vmware.memory = "512"
    vmware.cpus = "1"
    vmware.gui = true
    # vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
    # vmware.ssh_info_public = true
    # vmware.linked_clone = false
  end

  config.vm.define "dvergobbS" do |server|
    server.vm.hostname = "dvergobbS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision :shell, path: "scripts/server.sh"
  end

  config.vm.define "dvergobbSW" do |serverWorker|
    serverWorker.vm.hostname = "dvergobbSW"
    serverWorker.vm.network "private_network", ip: "192.168.56.111"
    serverWorker.vm.provision :shell, path: "scripts/serverWorker.sh"
  end
end
