# Get K3S_TOKEN from .env file
env_file_path = File.join(File.dirname(__FILE__), '.env')
if File.exist?(env_file_path)
  File.read(env_file_path).each_line do |line|
    key, value = line.strip.split('=')
    ENV[key] = value
  end
end

Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-12"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
    v.gui = false
  end

  config.vm.define "dvergobbS" do |server|
    server.vm.hostname = "dvergobbS"
    server.vm.network "private_network", bridge: "eth1", ip: "192.168.56.110"
    server.vm.provision "shell", inline: <<-SHELL
      # Script for Server
      sudo apt-get update
      sudo apt-get install -qqy curl net-tools

      # Add /sbin to the PATH for the user vagrant
      echo 'export PATH=$PATH:/sbin' >> /home/vagrant/.bashrc
      source /home/vagrant/.bashrc

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip 192.168.56.110" \
        K3S_TOKEN="#{ENV['K3S_TOKEN']}" \
        K3S_KUBECONFIG_MODE="644" sh -s -
    SHELL
  end

  config.vm.define "dvergobbSW" do |serverWorker|
    serverWorker.vm.hostname = "dvergobbSW"
      serverWorker.vm.network "private_network", bridge: "eth1", ip: "192.168.56.111"
      serverWorker.vm.provision "shell", inline: <<-SHELL
      # Script for ServerWorker
      sudo apt-get update
      sudo apt-get install -qqy curl net-tools

      # Add /sbin to the PATH for the user vagrant
      echo 'export PATH=$PATH:/sbin' >> /home/vagrant/.bashrc
      source /home/vagrant/.bashrc

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --node-ip 192.168.56.111" \
        K3S_URL=https://192.168.56.110:6443 \
        K3S_TOKEN="#{ENV['K3S_TOKEN']}" \
        K3S_KUBECONFIG_MODE="644" sh -s -
    SHELL
  end
end
